version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  nodeapi:
    build: .
    container_name: nodeapi
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver
    environment:
      - DB_USER=sa
      - DB_PASSWORD=yourStrong(!)Password
      - DB_SERVER=sqlserver
      - DB_DATABASE=your_database
      - DB_PORT=1433
      - DB_ENCRYPT=false
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
